version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '80:80'  # Public HTTP Port
      - '443:443'  # Public HTTPS Port
      - '81:81'  # Admin Web Port
    networks:
      br0:
        ipv4_address: 192.168.1.9
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  br0:
    external: true